### PR TITLE
add sourcemap js example

### PR DESCRIPTION
**Pull request by juliandescottes**
I always struggle to find a website to exercise js sourcemaps so here's a simple example that could be useful to have available.

### CODE REVIEW

**Comment by bgrins** [comment]
Thanks!  I always have problems finding good examples too.  Pushed to https://bgrins.github.io/devtools-demos/debugger/sourcemaps/

**Comment by bgrins** [comment]
@juliandescottes can you include the build scripts you used to generate the source maps so I can rebuild / update the test with more code if needed?

**Comment by juliandescottes** [comment]
@bgrins thanks for merging! 

>  can you include the build scripts

Sure, could be handy.

**Comment by jasonLaster** [comment]
by the way I'm now competing with @bgrins to host the best debugger examples

https://github.com/jasonLaster/debugger-examples

**Comment by bgrins** [comment]
Nice, would you be able to publish that on gh-pages or does it need the server to be running?  Would be great to be able to link to it

**Comment by jasonLaster** [comment]
Yup. Gh pages is the plan

**Pull request merged**
